{"name": "test_valid_login", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: A session is either terminated or not started; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#invalidsessionidexception\nStacktrace:\nNoSuchDriverError: A session is either terminated or not started\n    at asyncHandler (/home/ethan/.nvm/versions/node/v16.20.2/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:311:15)\n    at /home/ethan/.nvm/versions/node/v16.20.2/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:514:15\n    at Layer.handle [as handle_request] (/home/ethan/.nvm/versions/node/v16.20.2/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)\n    at next (/home/ethan/.nvm/versions/node/v16.20.2/lib/node_modules/appium/node_modules/express/lib/router/route.js:149:13)\n    at Route.dispatch (/home/ethan/.nvm/versions/node/v16.20.2/lib/node_modules/appium/node_modules/express/lib/router/route.js:119:3)\n    at Layer.handle [as handle_request] (/home/ethan/.nvm/versions/node/v16.20.2/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)\n    at /home/ethan/.nvm/versions/node/v16.20.2/lib/node_modules/appium/node_modules/express/lib/router/index.js:284:15\n    at param (/home/ethan/.nvm/versions/node/v16.20.2/lib/node_modules/appium/node_modules/express/lib/router/index.js:365:14)\n    at param (/home/ethan/.nvm/versions/node/v16.20.2/lib/node_modules/appium/node_modules/express/lib/router/index.js:376:14)\n    at Function.process_params (/home/ethan/.nvm/versions/node/v16.20.2/lib/node_modules/appium/node_modules/express/lib/router/index.js:421:3)\n    at next (/home/ethan/.nvm/versions/node/v16.20.2/lib/node_modules/appium/node_modules/express/lib/router/index.js:280:10)\n    at logger (/home/ethan/.nvm/versions/node/v16.20.2/lib/node_modules/appium/node_modules/morgan/index.js:144:5)\n    at Layer.handle [as handle_request] (/home/ethan/.nvm/versions/node/v16.20.2/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/home/ethan/.nvm/versions/node/v16.20.2/lib/node_modules/appium/node_modules/express/lib/router/index.js:328:13)\n    at /home/ethan/.nvm/versions/node/v16.20.2/lib/node_modules/appium/node_modules/express/lib/router/index.js:286:9\n    at Function.process_params (/home/ethan/.nvm/versions/node/v16.20.2/lib/node_modules/appium/node_modules/express/lib/router/index.js:346:12)\n    at next (/home/ethan/.nvm/versions/node/v16.20.2/lib/node_modules/appium/node_modules/express/lib/router/index.js:280:10)\n    at jsonParser (/home/ethan/.nvm/versions/node/v16.20.2/lib/node_modules/appium/node_modules/body-parser/lib/types/json.js:113:7)\n    at Layer.handle [as handle_request] (/home/ethan/.nvm/versions/node/v16.20.2/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/home/ethan/.nvm/versions/node/v16.20.2/lib/node_modules/appium/node_modules/express/lib/router/index.js:328:13)\n    at /home/ethan/.nvm/versions/node/v16.20.2/lib/node_modules/appium/node_modules/express/lib/router/index.js:286:9\n    at Function.process_params (/home/ethan/.nvm/versions/node/v16.20.2/lib/node_modules/appium/node_modules/express/lib/router/index.js:346:12)", "trace": "self = <allure_commons._allure.fixture object at 0x7f7f173d68f0>, args = ()\nkwargs = {}\n\n    def __call__(self, *args, **kwargs):\n        self.parameters = func_parameters(self._fixture_function, *args, **kwargs)\n    \n        with self:\n>           return self._fixture_function(*args, **kwargs)\n\n../.venv/lib/python3.10/site-packages/allure_commons/_allure.py:231: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nconftest.py:8: in driver\n    driver.quit()\n../.venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py:612: in quit\n    self.execute(Command.QUIT)\n../.venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py:454: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <appium.webdriver.errorhandler.MobileErrorHandler object at 0x7f7f173d7e80>\nresponse = {'status': 404, 'value': '{\"value\":{\"error\":\"invalid session id\",\"message\":\"A session is either terminated or not star... (/home/ethan/.nvm/versions/node/v16.20.2/lib/node_modules/appium/node_modules/express/lib/router/index.js:346:12)\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"\n        https://www.w3.org/TR/webdriver/#errors\n        \"\"\"\n        payload = response.get('value', '')\n        if isinstance(payload, dict):\n            payload_dict = payload\n        else:\n            try:\n                payload_dict = json.loads(payload)\n            except (json.JSONDecodeError, TypeError):\n                return\n            if not isinstance(payload_dict, dict):\n                return\n        value = payload_dict.get('value')\n        if not isinstance(value, dict):\n            return\n        error = value.get('error')\n        if not error:\n            return\n    \n        message = value.get('message', error)\n        stacktrace = value.get('stacktrace', '')\n        # In theory, we should also be checking HTTP status codes.\n        # Java client, for example, prints a warning if the actual `error`\n        # value does not match to the response's HTTP status code.\n        exception_class: Type[sel_exceptions.WebDriverException] = ERROR_TO_EXC_MAPPING.get(\n            error, sel_exceptions.WebDriverException\n        )\n        if exception_class is sel_exceptions.WebDriverException and message:\n            if message == 'No such context found.':\n                exception_class = appium_exceptions.NoSuchContextException\n            elif message == 'That command could not be executed in the current context.':\n                exception_class = appium_exceptions.InvalidSwitchToTargetException\n    \n        if exception_class is sel_exceptions.UnexpectedAlertPresentException:\n            raise sel_exceptions.UnexpectedAlertPresentException(\n                msg=message,\n                stacktrace=format_stacktrace(stacktrace),\n                alert_text=value.get('data'),\n            )\n>       raise exception_class(msg=message, stacktrace=format_stacktrace(stacktrace))\nE       selenium.common.exceptions.InvalidSessionIdException: Message: A session is either terminated or not started; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#invalidsessionidexception\nE       Stacktrace:\nE       NoSuchDriverError: A session is either terminated or not started\nE           at asyncHandler (/home/ethan/.nvm/versions/node/v16.20.2/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:311:15)\nE           at /home/ethan/.nvm/versions/node/v16.20.2/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:514:15\nE           at Layer.handle [as handle_request] (/home/ethan/.nvm/versions/node/v16.20.2/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)\nE           at next (/home/ethan/.nvm/versions/node/v16.20.2/lib/node_modules/appium/node_modules/express/lib/router/route.js:149:13)\nE           at Route.dispatch (/home/ethan/.nvm/versions/node/v16.20.2/lib/node_modules/appium/node_modules/express/lib/router/route.js:119:3)\nE           at Layer.handle [as handle_request] (/home/ethan/.nvm/versions/node/v16.20.2/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)\nE           at /home/ethan/.nvm/versions/node/v16.20.2/lib/node_modules/appium/node_modules/express/lib/router/index.js:284:15\nE           at param (/home/ethan/.nvm/versions/node/v16.20.2/lib/node_modules/appium/node_modules/express/lib/router/index.js:365:14)\nE           at param (/home/ethan/.nvm/versions/node/v16.20.2/lib/node_modules/appium/node_modules/express/lib/router/index.js:376:14)\nE           at Function.process_params (/home/ethan/.nvm/versions/node/v16.20.2/lib/node_modules/appium/node_modules/express/lib/router/index.js:421:3)\nE           at next (/home/ethan/.nvm/versions/node/v16.20.2/lib/node_modules/appium/node_modules/express/lib/router/index.js:280:10)\nE           at logger (/home/ethan/.nvm/versions/node/v16.20.2/lib/node_modules/appium/node_modules/morgan/index.js:144:5)\nE           at Layer.handle [as handle_request] (/home/ethan/.nvm/versions/node/v16.20.2/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)\nE           at trim_prefix (/home/ethan/.nvm/versions/node/v16.20.2/lib/node_modules/appium/node_modules/express/lib/router/index.js:328:13)\nE           at /home/ethan/.nvm/versions/node/v16.20.2/lib/node_modules/appium/node_modules/express/lib/router/index.js:286:9\nE           at Function.process_params (/home/ethan/.nvm/versions/node/v16.20.2/lib/node_modules/appium/node_modules/express/lib/router/index.js:346:12)\nE           at next (/home/ethan/.nvm/versions/node/v16.20.2/lib/node_modules/appium/node_modules/express/lib/router/index.js:280:10)\nE           at jsonParser (/home/ethan/.nvm/versions/node/v16.20.2/lib/node_modules/appium/node_modules/body-parser/lib/types/json.js:113:7)\nE           at Layer.handle [as handle_request] (/home/ethan/.nvm/versions/node/v16.20.2/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)\nE           at trim_prefix (/home/ethan/.nvm/versions/node/v16.20.2/lib/node_modules/appium/node_modules/express/lib/router/index.js:328:13)\nE           at /home/ethan/.nvm/versions/node/v16.20.2/lib/node_modules/appium/node_modules/express/lib/router/index.js:286:9\nE           at Function.process_params (/home/ethan/.nvm/versions/node/v16.20.2/lib/node_modules/appium/node_modules/express/lib/router/index.js:346:12)\n\n../.venv/lib/python3.10/site-packages/appium/webdriver/errorhandler.py:125: InvalidSessionIdException"}, "start": 1753965244853, "stop": 1753965253741, "uuid": "3581c62d-fa40-4091-8d71-b7dbe17c989b", "historyId": "ab68c09e23714aa68c720c2ca07c0ecf", "testCaseId": "ab68c09e23714aa68c720c2ca07c0ecf", "fullName": "tests.test_login#test_valid_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "ubuntu"}, {"name": "thread", "value": "2230033-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}], "titlePath": ["tests", "test_login.py"]}